spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 10000

  ####################################################################################################
  ## test 전용 환경
  ####################################################################################################

  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    generate-ddl: off

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
    initialization-mode: always
    schema: classpath:schema-h2.sql
    data: classpath:data-h2.sql